import { pgTable, index, unique, pgPolicy, uuid, varchar, text, timestamp, bigserial, foreignKey, boolean, jsonb, numeric, integer } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const shops = pgTable("shops", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: varchar("shop_domain", { length: 255 }).notNull(),
	accessToken: text("access_token").notNull(),
	scope: text(),
	primaryDomain: varchar("primary_domain", { length: 255 }),
	installedAt: timestamp("installed_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	uninstalledAt: timestamp("uninstalled_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("idx_shops_domain").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	unique("shops_shop_domain_unique").on(table.shopDomain),
	pgPolicy("Service role has full access to shops", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'service_role'::text)` }),
]);

export const customers = pgTable("customers", {
	id: bigserial({ mode: "bigint" }).primaryKey().notNull(),
	shopDomain: text("shop_domain").notNull(),
	phone: text().notNull(),
	name: text().notNull(),
	address: text(),
	state: text(),
	city: text(),
	zipcode: text(),
	email: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_customers_shop_phone").using("btree", table.shopDomain.asc().nullsLast().op("text_ops"), table.phone.asc().nullsLast().op("text_ops")),
	index("idx_customers_updated_at").using("btree", table.updatedAt.desc().nullsFirst().op("timestamptz_ops")),
	unique("customers_shop_phone_unique").on(table.shopDomain, table.phone),
	pgPolicy("Allow all operations on customers", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
]);

export const integrationSettings = pgTable("integration_settings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: varchar("shop_domain", { length: 255 }).notNull(),
	integrationId: varchar("integration_id", { length: 100 }).notNull(),
	enabled: boolean().default(false),
	connected: boolean().default(false),
	connectedEmail: varchar("connected_email", { length: 255 }),
	accessToken: text("access_token"),
	refreshToken: text("refresh_token"),
	tokenExpiresAt: timestamp("token_expires_at", { withTimezone: true, mode: 'string' }),
	config: jsonb().default({}),
	connectedAt: timestamp("connected_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_integration_settings_enabled").using("btree", table.enabled.asc().nullsLast().op("bool_ops")).where(sql`(enabled = true)`),
	index("idx_integration_settings_integration").using("btree", table.integrationId.asc().nullsLast().op("text_ops")),
	index("idx_integration_settings_shop").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.shopDomain],
			foreignColumns: [shops.shopDomain],
			name: "fk_integration_settings_shop"
		}).onDelete("cascade"),
	unique("integration_settings_unique").on(table.shopDomain, table.integrationId),
	pgPolicy("Service role has full access to integration_settings", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'service_role'::text)` }),
]);

export const upsellOffers = pgTable("upsell_offers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: text("shop_domain").notNull(),
	type: text().default('click_upsell').notNull(),
	campaignName: text("campaign_name").default('').notNull(),
	active: boolean().default(true),
	upsellMode: text("upsell_mode").default('post_purchase'),
	showConditionType: text("show_condition_type").default('always'),
	triggerProductIds: jsonb("trigger_product_ids").default([]),
	minOrderValue: numeric("min_order_value").default('0'),
	maxOrderValue: numeric("max_order_value").default('0'),
	offers: jsonb().default([]),
	design: jsonb().default({}),
	linkedDownsellId: uuid("linked_downsell_id"),
	displayLocation: text("display_location").default('in_form'),
	checkboxDefaultChecked: boolean("checkbox_default_checked").default(false),
	priority: integer().default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	formCloseCount: integer("form_close_count").default(1),
}, (table) => [
	index("idx_upsell_offers_active").using("btree", table.shopDomain.asc().nullsLast().op("text_ops"), table.active.asc().nullsLast().op("bool_ops")),
	index("idx_upsell_offers_shop").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	index("idx_upsell_offers_type").using("btree", table.shopDomain.asc().nullsLast().op("text_ops"), table.type.asc().nullsLast().op("text_ops")),
	pgPolicy("upsell_offers_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`true` }),
	pgPolicy("upsell_offers_insert", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("upsell_offers_select", { as: "permissive", for: "select", to: ["public"] }),
	pgPolicy("upsell_offers_update", { as: "permissive", for: "update", to: ["public"] }),
]);

export const quantityOfferGroups = pgTable("quantity_offer_groups", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: varchar("shop_domain", { length: 255 }).notNull(),
	name: varchar({ length: 255 }).default('New Quantity Offer').notNull(),
	active: boolean().default(false),
	productIds: jsonb("product_ids").default([]),
	offers: jsonb().default([]),
	design: jsonb().default({}),
	placement: varchar({ length: 50 }).default('inside_form'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_quantity_offers_active").using("btree", table.active.asc().nullsLast().op("bool_ops")),
	index("idx_quantity_offers_products").using("gin", table.productIds.asc().nullsLast().op("jsonb_ops")),
	index("idx_quantity_offers_shop").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	index("idx_quantity_offers_updated").using("btree", table.updatedAt.desc().nullsFirst().op("timestamptz_ops")),
	foreignKey({
			columns: [table.shopDomain],
			foreignColumns: [shops.shopDomain],
			name: "fk_quantity_offers_shop"
		}).onDelete("cascade"),
	pgPolicy("Service role has full access to quantity_offer_groups", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'service_role'::text)` }),
]);

export const shippingRates = pgTable("shipping_rates", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: text("shop_domain").notNull(),
	name: text().notNull(),
	description: text(),
	price: numeric().default('0').notNull(),
	conditionType: text("condition_type").default('none'),
	minValue: numeric("min_value"),
	maxValue: numeric("max_value"),
	appliesToProducts: boolean("applies_to_products").default(false),
	productIds: text("product_ids").array().default([""]),
	appliesToCountries: boolean("applies_to_countries").default(false),
	countryCodes: text("country_codes").array().default([""]),
	appliesToStates: boolean("applies_to_states").default(false),
	stateCodes: text("state_codes").array().default([""]),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	appliesToCollections: boolean("applies_to_collections").default(false),
	collectionIds: text("collection_ids").array().default([""]),
}, (table) => [
	index("idx_shipping_rates_active").using("btree", table.shopDomain.asc().nullsLast().op("text_ops"), table.isActive.asc().nullsLast().op("text_ops")),
	index("idx_shipping_rates_shop").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	pgPolicy("shop_shipping_rates_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(shop_domain = current_setting('request.jwt.claims.shop_domain'::text, true))` }),
	pgPolicy("shop_shipping_rates_insert", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("shop_shipping_rates_select", { as: "permissive", for: "select", to: ["public"] }),
	pgPolicy("shop_shipping_rates_update", { as: "permissive", for: "update", to: ["public"] }),
]);

export const formSettings = pgTable("form_settings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: varchar("shop_domain", { length: 255 }).notNull(),
	enabled: boolean().default(false),
	buttonText: varchar("button_text", { length: 100 }).default('Order Now (COD)'),
	primaryColor: varchar("primary_color", { length: 7 }).default('#000000'),
	requiredFields: jsonb("required_fields").default(["name","phone","address"]),
	maxQuantity: integer("max_quantity").default(10),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	buttonStyle: text("button_style").default('solid'),
	buttonSize: text("button_size").default('large'),
	buttonPosition: text("button_position").default('below_atc'),
	formTitle: text("form_title").default('Cash on Delivery Order'),
	formSubtitle: text("form_subtitle").default('Fill in your details to place a COD order'),
	successMessage: text("success_message").default('Your order has been placed! We will contact you shortly.'),
	submitButtonText: text("submit_button_text").default('Place COD Order'),
	showProductImage: boolean("show_product_image").default(true),
	showPrice: boolean("show_price").default(true),
	showQuantitySelector: boolean("show_quantity_selector").default(true),
	showEmailField: boolean("show_email_field").default(false),
	showNotesField: boolean("show_notes_field").default(false),
	emailRequired: boolean("email_required").default(false),
	namePlaceholder: text("name_placeholder").default('Enter your full name'),
	phonePlaceholder: text("phone_placeholder").default('Enter your phone number'),
	addressPlaceholder: text("address_placeholder").default('Enter your delivery address'),
	notesPlaceholder: text("notes_placeholder").default('Any special instructions?'),
	modalStyle: text("modal_style").default('modern'),
	animationStyle: text("animation_style").default('fade'),
	borderRadius: integer("border_radius").default(12),
	formBackgroundColor: varchar("form_background_color", { length: 20 }).default('#ffffff'),
	fieldBackgroundColor: varchar("field_background_color", { length: 20 }).default('#f9fafb'),
	labelColor: varchar("label_color", { length: 20 }).default('#374151'),
	baseFontSize: integer("base_font_size").default(14),
	fieldOrder: jsonb("field_order").default(["name","phone","address","email","notes"]),
	inputTextColor: varchar("input_text_color", { length: 7 }).default('#111827'),
	labelFontSize: varchar("label_font_size", { length: 20 }).default('medium'),
	inputFontSize: varchar("input_font_size", { length: 20 }).default('medium'),
	titleFontSize: varchar("title_font_size", { length: 20 }).default('large'),
	formType: varchar("form_type", { length: 20 }).default('popup'),
	buttonSubtitle: text("button_subtitle"),
	buttonTextColor: varchar("button_text_color", { length: 7 }).default('#ffffff'),
	buttonTextSize: integer("button_text_size").default(16),
	buttonTextBold: boolean("button_text_bold").default(true),
	buttonTextItalic: boolean("button_text_italic").default(false),
	buttonBorderColor: varchar("button_border_color", { length: 7 }).default('#ffffff'),
	buttonBorderWidth: integer("button_border_width").default(0),
	buttonBorderRadius: integer("button_border_radius").default(8),
	buttonShadow: integer("button_shadow").default(0),
	buttonAnimation: varchar("button_animation", { length: 20 }).default('none'),
	formTextColor: varchar("form_text_color", { length: 7 }).default('#000000'),
	formTextSize: integer("form_text_size").default(16),
	formTextBold: boolean("form_text_bold").default(false),
	formTextItalic: boolean("form_text_italic").default(false),
	formLabelAlignment: varchar("form_label_alignment", { length: 10 }).default('left'),
	formBorderColor: varchar("form_border_color", { length: 7 }).default('#000000'),
	formBorderWidth: integer("form_border_width").default(0),
	formBorderRadius: integer("form_border_radius").default(8),
	formShadow: integer("form_shadow").default(0),
	formIconColor: varchar("form_icon_color", { length: 7 }).default('#212529'),
	formIconBackground: varchar("form_icon_background", { length: 7 }).default('#e1e1e1'),
	hideFieldLabels: boolean("hide_field_labels").default(false),
	allowedCountries: jsonb("allowed_countries").default([]),
	fields: jsonb().default([{"id":"name","type":"text","label":"Full Name","order":1,"visible":true,"required":true},{"id":"phone","type":"tel","label":"Phone Number","order":2,"visible":true,"required":true},{"id":"address","type":"textarea","label":"Address","order":3,"visible":true,"required":true},{"id":"zip","type":"text","label":"ZIP Code","order":4,"visible":false,"required":false},{"id":"state","type":"text","label":"State","order":5,"visible":false,"required":false},{"id":"city","type":"text","label":"City","order":6,"visible":false,"required":false},{"id":"email","type":"email","label":"Email","order":7,"visible":false,"required":false},{"id":"notes","type":"textarea","label":"Notes","order":8,"visible":false,"required":false},{"id":"quantity","type":"number","label":"Quantity","order":9,"visible":true,"required":false},{"id":"marketing","type":"checkbox","label":"Buyer accepts marketing","order":10,"visible":false,"required":false}]),
	blocks: jsonb().default({"order_summary":true,"buyer_marketing":false,"shipping_options":false,"cart_quantity_offers":false}),
	customFields: jsonb("custom_fields").default([]),
	styles: jsonb().default({"shadow":true,"iconColor":"#6366f1","textColor":"#333333","borderRadius":12,"iconBackground":"#f3f4f6","labelAlignment":"left","backgroundColor":"#ffffff"}),
	buttonStyles: jsonb("button_styles").default({"shadow":true,"animation":"none","textColor":"#ffffff","borderColor":"#6366f1","borderWidth":0,"borderRadius":12,"backgroundColor":"#6366f1"}),
	shippingOptions: jsonb("shipping_options").default({"enabled":false,"options":[{"id":"free_shipping","label":"Free Shipping","price":0},{"id":"standard","label":"Standard Shipping","price":50},{"id":"express","label":"Express Shipping","price":100}],"defaultOption":"free_shipping"}),
	partialCodEnabled: boolean("partial_cod_enabled").default(false),
	partialCodAdvanceAmount: integer("partial_cod_advance_amount").default(100),
	partialCodCommission: numeric("partial_cod_commission", { precision: 10, scale:  2 }).default('0'),
	shippingRatesEnabled: boolean("shipping_rates_enabled").default(false),
	formSubmitButton: jsonb("form_submit_button"),
	enableCouponField: boolean("enable_coupon_field").default(false),
	couponFieldPosition: integer("coupon_field_position").default(13),
	coupons: jsonb().default([]),
}, (table) => [
	index("idx_form_settings_shop").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.shopDomain],
			foreignColumns: [shops.shopDomain],
			name: "fk_form_settings_shop"
		}).onDelete("cascade"),
	unique("form_settings_shop_domain_unique").on(table.shopDomain),
	pgPolicy("Service role has full access to form_settings", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'service_role'::text)` }),
]);

export const pixelTrackingSettings = pgTable("pixel_tracking_settings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: text("shop_domain").notNull(),
	provider: text().notNull(),
	label: text(),
	pixelId: text("pixel_id"),
	accessToken: text("access_token"),
	conversionApiToken: text("conversion_api_token"),
	trackInitiateCheckout: boolean("track_initiate_checkout").default(true),
	trackPurchase: boolean("track_purchase").default(true),
	trackAddToCart: boolean("track_add_to_cart").default(false),
	trackViewContent: boolean("track_view_content").default(false),
	trackAddPaymentInfo: boolean("track_add_payment_info").default(false),
	enabled: boolean().default(true),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("pixel_tracking_shop_domain_idx").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
]);

export const fraudProtectionSettings = pgTable("fraud_protection_settings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: text("shop_domain").notNull(),
	limitOrdersEnabled: boolean("limit_orders_enabled").default(false),
	maxOrders: integer("max_orders"),
	limitHours: integer("limit_hours"),
	limitQuantityEnabled: boolean("limit_quantity_enabled").default(false),
	maxQuantity: integer("max_quantity"),
	blockedPhoneNumbers: text("blocked_phone_numbers").array().default([""]),
	blockedEmails: text("blocked_emails").array().default([""]),
	blockedIpAddresses: text("blocked_ip_addresses").array().default([""]),
	allowedIpAddresses: text("allowed_ip_addresses").array().default([""]),
	postalCodeMode: text("postal_code_mode").default('none'),
	postalCodes: text("postal_codes").array().default([""]),
	blockedMessage: text("blocked_message").default('Sorry, you are not allowed to place orders.'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("fraud_protection_shop_domain_idx").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	unique("fraud_protection_settings_shop_domain_key").on(table.shopDomain),
]);

export const merchantSubscriptions = pgTable("merchant_subscriptions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shop: varchar("shop", { length: 255 }).notNull(),
	shopifySubscriptionId: varchar("shopify_subscription_id", { length: 255 }),
	shopifyUsageLineItemId: varchar("shopify_usage_line_item_id", { length: 255 }),
	planName: varchar("plan_name", { length: 50 }).default('FREE').notNull(),
	billingCycle: varchar("billing_cycle", { length: 20 }).default('monthly').notNull(),
	status: varchar({ length: 30 }).default('active').notNull(),
	renewsOn: timestamp("renews_on", { withTimezone: true, mode: 'string' }),
	usageCappedAmount: numeric("usage_capped_amount", { precision: 10, scale: 2 }).default('0').notNull(),
	isTest: boolean("is_test").default(false).notNull(),
	cancelledAt: timestamp("cancelled_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	cancelAtPeriodEnd: boolean("cancel_at_period_end").default(false).notNull(),
	cancelRequestedAt: timestamp("cancel_requested_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("idx_merchant_subscriptions_shop").using("btree", table.shop.asc().nullsLast().op("text_ops")),
	index("idx_merchant_subscriptions_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	unique("merchant_subscriptions_shop_key").on(table.shop),
]);

export const merchantUsageCycles = pgTable("merchant_usage_cycles", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shop: varchar("shop", { length: 255 }).notNull(),
	planName: varchar("plan_name", { length: 50 }).default('FREE').notNull(),
	cycleStart: timestamp("cycle_start", { withTimezone: true, mode: 'string' }).notNull(),
	cycleEnd: timestamp("cycle_end", { withTimezone: true, mode: 'string' }).notNull(),
	includedOrdersUsed: integer("included_orders_used").default(0).notNull(),
	overageOrders: integer("overage_orders").default(0).notNull(),
	overageChargedOrders: integer("overage_charged_orders").default(0).notNull(),
	lastUsageChargeDate: timestamp("last_usage_charge_date", { withTimezone: true, mode: 'string' }),
	status: varchar({ length: 20 }).default('active').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_merchant_usage_cycles_shop").using("btree", table.shop.asc().nullsLast().op("text_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
]);

export const otpSettings = pgTable("otp_settings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: text("shop_domain").notNull(),
	mode: text().default('disabled').notNull(),
	expirySeconds: integer("expiry_seconds").default(300).notNull(),
	resendCooldownSeconds: integer("resend_cooldown_seconds").default(60).notNull(),
	maxAttempts: integer("max_attempts").default(5).notNull(),
	postOrderCod: boolean("post_order_cod").default(true).notNull(),
	postOrderPartial: boolean("post_order_partial").default(true).notNull(),
	postOrderPrepaid: boolean("post_order_prepaid").default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_otp_settings_shop").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	unique("otp_settings_shop_domain_key").on(table.shopDomain),
]);

export const shopifySessions = pgTable("shopify_sessions", {
	id: text().primaryKey().notNull(),
	shop: text().notNull(),
	state: text(),
	isOnline: boolean("is_online").default(false),
	scope: text(),
	accessToken: text("access_token"),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'string' }),
	onlineAccessInfo: jsonb("online_access_info"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	refreshToken: text("refresh_token"),
	refreshTokenExpires: timestamp("refresh_token_expires", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("idx_shopify_sessions_shop").using("btree", table.shop.asc().nullsLast().op("text_ops")),
]);

export const orderLogs = pgTable("order_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	shopDomain: varchar("shop_domain", { length: 255 }).notNull(),
	shopifyOrderId: varchar("shopify_order_id", { length: 255 }),
	shopifyOrderName: varchar("shopify_order_name", { length: 255 }),
	customerName: varchar("customer_name", { length: 255 }),
	customerPhone: varchar("customer_phone", { length: 50 }),
	customerAddress: text("customer_address"),
	productId: varchar("product_id", { length: 255 }),
	productTitle: varchar("product_title", { length: 255 }),
	variantId: varchar("variant_id", { length: 255 }),
	quantity: integer().default(1),
	totalPrice: numeric("total_price", { precision: 10, scale:  2 }),
	currency: varchar({ length: 10 }).notNull(),
	status: varchar({ length: 50 }).default('pending'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	customerEmail: varchar("customer_email", { length: 255 }),
	customerNotes: text("customer_notes"),
	city: text(),
	state: text(),
	pincode: text(),
	isPartialCod: boolean("is_partial_cod").default(false),
	advanceAmount: numeric("advance_amount", { precision: 10, scale:  2 }),
	remainingCodAmount: numeric("remaining_cod_amount", { precision: 10, scale:  2 }),
	shippingLabel: varchar("shipping_label", { length: 255 }),
	shippingPrice: numeric("shipping_price", { precision: 10, scale:  2 }).default('0'),
	syncStatus: text("sync_status").default('pending_sync'),
	syncAttempts: integer("sync_attempts").default(0),
	syncError: text("sync_error"),
	lastSyncedAt: timestamp("last_synced_at", { withTimezone: true, mode: 'string' }),
	nextRetryAt: timestamp("next_retry_at", { withTimezone: true, mode: 'string' }),
	orderPayload: jsonb("order_payload"),
	couponCode: varchar("coupon_code", { length: 100 }),
	discountAmount: numeric("discount_amount", { precision: 10, scale:  2 }).default('0'),
	originalTotal: numeric("original_total", { precision: 10, scale:  2 }),
	finalTotal: numeric("final_total", { precision: 10, scale:  2 }),
	isFullPrepaid: boolean("is_full_prepaid").default(false),
	paymentMethod: text("payment_method").default('cod'),
}, (table) => [
	index("idx_order_logs_coupon_code").using("btree", table.shopDomain.asc().nullsLast().op("text_ops"), table.couponCode.asc().nullsLast().op("text_ops")),
	index("idx_order_logs_created").using("btree", table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_order_logs_partial_cod").using("btree", table.isPartialCod.asc().nullsLast().op("bool_ops")),
	index("idx_order_logs_payment_method").using("btree", table.shopDomain.asc().nullsLast().op("text_ops"), table.paymentMethod.asc().nullsLast().op("text_ops")),
	index("idx_order_logs_shop").using("btree", table.shopDomain.asc().nullsLast().op("text_ops")),
	index("idx_order_logs_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.shopDomain],
			foreignColumns: [shops.shopDomain],
			name: "fk_order_logs_shop"
		}).onDelete("set null"),
	pgPolicy("Allow update for all", { as: "permissive", for: "update", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("Service role has full access to order_logs", { as: "permissive", for: "all", to: ["public"] }),
]);

export const partialPaymentSettings = pgTable("partial_payment_settings", {
	id: bigserial({ mode: "bigint" }).primaryKey().notNull(),
	shopDomain: text("shop_domain").notNull(),
	enabled: boolean().default(false).notNull(),
	paymentOptions: jsonb("payment_options").default([]).notNull(),
	codFeeEnabled: boolean("cod_fee_enabled").default(false).notNull(),
	codFeeName: text("cod_fee_name").default('COD Fee').notNull(),
	codFeeType: text("cod_fee_type").default('fixed').notNull(),
	codFeeAmount: numeric("cod_fee_amount", { precision: 10, scale:  2 }).default('0').notNull(),
	minimumOrderTotal: numeric("minimum_order_total", { precision: 10, scale:  2 }).default('0').notNull(),
	maximumOrderTotal: numeric("maximum_order_total", { precision: 10, scale:  2 }).default('0').notNull(),
	allowedProductIds: jsonb("allowed_product_ids").default([]).notNull(),
	allowedCollectionIds: jsonb("allowed_collection_ids").default([]).notNull(),
	allowedCountries: jsonb("allowed_countries").default([]).notNull(),
	excludedCountries: jsonb("excluded_countries").default([]).notNull(),
	modalSettings: jsonb("modal_settings").default({}).notNull(),
	moduleFlags: jsonb("module_flags").default({"apply_coupons_to_partial":true,"apply_upsells_to_partial":true,"apply_bundle_discounts_to_partial":true}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	fullPrepaidEnabled: boolean("full_prepaid_enabled").default(false),
	fullPrepaidMinimumOrderTotal: numeric("full_prepaid_minimum_order_total").default('0'),
	fullPrepaidMaximumOrderTotal: numeric("full_prepaid_maximum_order_total").default('0'),
	fullPrepaidAllowedProductIds: jsonb("full_prepaid_allowed_product_ids").default([]),
	fullPrepaidAllowedCollectionIds: jsonb("full_prepaid_allowed_collection_ids").default([]),
	prepaidDiscountEnabled: boolean("prepaid_discount_enabled").default(false),
	prepaidDiscountType: text("prepaid_discount_type").default('percentage'),
	prepaidDiscountValue: numeric("prepaid_discount_value", { precision: 10, scale:  2 }).default('0'),
	pureCodEnabled: boolean("pure_cod_enabled").default(false),
	pureCodFeeEnabled: boolean("pure_cod_fee_enabled").default(false),
	pureCodFeeName: text("pure_cod_fee_name").default('COD Fee'),
	pureCodFeeType: text("pure_cod_fee_type").default('fixed'),
	pureCodFeeAmount: numeric("pure_cod_fee_amount").default('0'),
	pureCodMinimumOrderTotal: numeric("pure_cod_minimum_order_total").default('0'),
	pureCodMaximumOrderTotal: numeric("pure_cod_maximum_order_total").default('0'),
	pureCodAllowedProductIds: jsonb("pure_cod_allowed_product_ids").default([]),
	pureCodAllowedCollectionIds: jsonb("pure_cod_allowed_collection_ids").default([]),
	countryRestrictions: jsonb("country_restrictions").default({"full_cod":{"allowedCountries":[],"excludedCountries":[]},"full_prepaid":{"allowedCountries":[],"excludedCountries":[]},"partial_payment":{"allowedCountries":[],"excludedCountries":[]}}),
}, (table) => [
	unique("partial_payment_settings_shop_domain_key").on(table.shopDomain),
]);
